apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend-service
  namespace: todo-app-space
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      nodePort: 30001
      targetPort: 8080

