apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-service
  namespace: todo-app-space
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000
      nodePort: 30002
      targetPort: 5000

