apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-app-pv
  namespace: todo-app-space
  labels:
    app: todo-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/mysql-data
    server: 192.168.5.128
